PREFIX bi: <http://example.org/biointegrate/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?geneSymbol ?uniprotId ?goId ?goLabel
WHERE {

  ?gene rdf:type bi:Gene .
  ?gene bi:geneSymbol ?geneSymbol .
  
  # In the TTL data, the link is defined from Protein to Gene
  ?protein bi:proteinProductOf ?gene .

  ?protein rdf:type bi:Protein .
  ?protein bi:uniprotId ?uniprotId .
  
  { ?protein bi:hasBiologicalProcess ?goTerm . }
  UNION
  { ?protein bi:hasCellularComponent ?goTerm . }
  UNION
  { ?protein bi:hasMolecularFunction ?goTerm . }

  ?goTerm bi:goId ?goId .
  ?goTerm bi:goLabel ?goLabel .

  FILTER(STR(?geneSymbol) = "MXRA5")
}